Map<String,String> en= {

  "locationSetTxt":"Location not set,click on icon!",
  "engTxt":"English",
  "gujTxt":"Gujarati",
  "hinTxt":"Hindi",
  "usgMapTxt" :"Use Google Maps",
  "usgManuallyTxt":"Enter Manually",
  "manuallyEntryTxt":"Manually Entry",
  "stdConveLocationTxt":"Enter location below in degrees using standard conventions",
  "notEstSouWesTxt":"(+ve for North/East and -ve for south/west)",
  "locationUseTxt":"Use this location",
  "mapLocationUseTxt":"See this location on map",
  "noTxt":"NO",
  "latiTxt":"Latitude:",
  "longTxt":"Longitude:",
  "selectTxt":"SELECT",
  "mapTxt":"map",
  "mapViewTxt":"Map View",
  "satelliteTxt":"Satellite",
  "searchTxt":"Search location",
  "searchBtnTxt" : "Search",
  "welcomeTxt":"WELCOME",
  "getStartTxt":"Let’s Get Started",
  "languageChooseTxt":"Choose Your Language",
  "languageUseTxt":"Select the language you prefer to use",
  "submitBtnTxt":"Submit",
  "mantraTxt":"Mantra",
  "teamAgnihotraTxt":"Team Agnihotra",
  "languageTxt":"Language",
  "aboutTxt":"About",
  "privacyPolicyTxt":"Privacy policy",
  "shareTxt":"Share",
  "helpTxt":"Help",
  "sunriseTxt":"Sunrise Mantra",
  "sunsetTxt":"Sunset Mantra",
  "playTxt":"Play it",
  "pauseTxt":'Pause it',
  "checkTimeTxt":"Ensure your time",
  "checkDeviceTimeTxt":"check your device time with time on the internet.please note that accuracy is dependent on network and third party tools-worldtimeapi.org internet.",
  "screenOnTxt":"Screen Always On",
  "screenKeepTxt":"Keeps screen awake while app is open",
  "hoursTxt":"24 Hours Clock",
  "timeTxt":"Change time format to 12 or 24 hours",
  "meditationTxt":"Meditation Bell",
  "ringsTxt":"Rings bell at time of Agnihotra",
  "countDownTxt":"Display Countdown",
  "countDownClockTxt":"Display countdown or clock in center",
  "reminderTxt":"Reminders For Sunset Time",
  "sunriseReminderTxt":"Reminders For Sunrise Time",
  "setReminderTxt":"Set Reminder for Agnihotra",
  "enterTimeInMinText":"Enter time in minutes (2-120):",
  "resetBtnTxt":"Reset",
  "deleteLocationTxt":"Delete All Location",
  "addLocationTxt":"Add Location",
  "sooryayaSwaha":"sooryaya swaha",
  "sooryayaIdem":"sooryaya idem na mama",
  "prajapatayeSwaha":"Prajapataye Swaha",
  "prajapatayeIdem":"prajapataye idem na mama",
  "agnayeSwaha":"agnaye swaha",
  "agnayeIdem":"agnaye idem na mama",
  "agnihotraMantraTxt":"Agnihotra",
  "agnihotraPatraText":"Agnihotra Patra Size",
  "sunriseSunsetMantraTxt":".... Sunrise & Sunset Mantra....",
  "tilakSandhyaMantraTxt":"Trikal sandhya mantra",
  "trikalMantraTxt":"Trikal Sandhya",
  "mantra24":"24 mantra",
  "timeZonTxt" :"Please confirm timezone\nfor this location",
  "standardTime":"India Standard Time(Asia/Kolkata)",
  "changeTimeTxt" : "Change Timezone",
  "confirmTimeZone" : "Confirm Timezone for your location",
  "yesTxt" : "YES",
  "timingDownload" : "Please wait,\ntiming are being downloaded.",
  "deleteAllLocation" : "Are you sure you wish to delete all\nlocations ?",
  "deleteThisLocation" : "Delete this Location?",
  "confirmTxt":"Confirm",
  "renameLocationBtnTxt":"RENAME THIS LOCATION",
  "renameLocationTxt":"Rename this Location",
  "deleteLocationBtnTxt" : "Delete this Location",
  "enterLocationTxt":"Enter new name for location",
  "cancleTxt":"CANCEL",
  "languageValidationTxt":"Please Selected Language",
  "latitudeIsRequired":"Latitude is required",
  "validLatitude":"Enter Valid Latitude",
  "longitudeIsRequired":"Longitude is required",
  "validLongitude":"Enter Valid Latitude",
  "searchText":"Search",
  "drinkWaterText":"(Drink Water)",
  "sprinklingWaterText":"(Sprinkling Water on Head)",
  "headText":"(Touch The Head)",
  "noseText":"(Touch The Nose)",
  "heartText":"(Touch The Heart)",
  "handsText":"(Hands With Sandwiched Palms On Right Knee)",
  "rightHandsText":"(Water In Right Hand)",
  "gayatriMantraText":"(3 time Gayatri Mantra)",
  "waterOblationText":"(Water Oblations)",
  "avahanMudraText":"(Avahan Mudra)",
  "meditateText":"(Meditate for Few Minutes, Start the gayatri japa and after that Meditate for some time)",
  "directionText":"(Stand Up, Bow Towards The Four Direction)",
  "fireText":"(Light The Fire)",
  "pourWaterText":"(Pour Water In Following Directions)",
  "samidhaText":"(Offer Samidha)",
  "timeText":"(3/7/11 Times)",
  "oneTimeText":"(1 Times)",
  "sandipText":"(SANDIP)",
  "surrenderingText":"(Surrendering all our actions thought & their results,\noffering water)",
  "roundText":"प्राणायामे विनियोगः (5 Round)",
  "eastText":"सन्ध्यायै नमः  - East",
  "southText":"सावित्रै नमः  - South",
  "gaytrenamText":"गायत्रै नमः  - West",
  "sarswateyText":"सरस्वत्यै नमः  - North",
  "sarvabyaText":"सर्वाभ्यो देवताभ्यो नमः  - East",
  "kamkarshitText":"कामोकार्षीत मन्युर्कार्षीत नमो नमः   - East",
  "aditeText":"ॐ अदितेन्वमंस्ताः ॥ \n(Pronounce As : अदितेन्वमग्गुस्ताः)",
  "anumatveText":"ॐ अनुमतेन्वमंस्ताः ॥ \n(Pronounce As : अनुमतेन्वमग्गुस्ताः)",
  "sarswateProText":"ॐ सरस्वतेन्वमंस्ताः ||\n(Pronounce As  : सरस्वतेन्वमग्गुस्ताः)",
  "applyText":"(Apply Ashes)",
  "meghaviText":"मेधावी भूयासम्\t\t\t\t\t\t\t\t\t\tOn Fore Head(Third Eye)",
  "tejasviText":"तेजस्वी भूयासम्\t\t\t\t\t\t\t\t\tOn Chest (Heart region)",
  "varchsviText":"वर्चस्वी भूयासम्\t\t\t\t\t\t\t\t\t\tRight Shoulder",
  "brhamsviText":"ब्रह्मवर्चस्वी भूयासम\t\t\t\t\tLeft Shoulder",
  "ayushyaText":"आयुष्यमान् भूयासम्\t\t\t\tNavel Region",
  "annadoText":"अन्नादो भूयासम्\t\t\t\t\t\t\t\t\t\tOn Throat",
  "swstiText":"स्वस्ति भूयासम्\t\t\t\t\t\t\t\t\t\t\tTop Of The Head",
  "settingsScreenTxt":"Settings",

  "processedTxt":"PROCEED",


  "SettingsScreenTxt":"Settings",




  "proceedTxt":"PROCEED",
  "indiaStdTime":"India Standard Time",
  "appName": "Agnihotra - A Disease Free Campaign",
  "inspiration": "Inspiration:",
  "guruName": "Gurudev Sri Sri Ravi Shankar",

  "alertTxt": 'Alert !',
  'resetButtonNotice':
  '\tYou are about to RESET the app which will delete all location timing and preference. You will be able to add new location post-reset.Use this option only in case of data corruption or error.',
  "resetMsg":"Reset Complete",
  "ringAlarmTxt" : 'Set reminders at',
   "search":'Search',
  "callHelpLine":'Call Helpline',
  "emailSupport":'Email Support',
  "chatSupport":'Chat with Support',
  "feedback":'Feedback',
  "feedbackOptionTxt":"Please select an option to share a feedback or convey a botheration" ,
  "shareFeedbackTxt":"I wish to share a feedback",
  "shareBotherationTxt":"I wish to convey botheration",
  "sendBtnTxt":"Send",
  "matraTxt":"Mantra",

  //Login Screen
  "doNotHaveAccountTxt":"You Don’t have any account?",
  "loginTxt":'Log in',
  "orSignInWithTxt":'Or sign in with',
  "continueGoogleTxt":"Continue with google",
  "orTxt":"OR",
  "logInWithTxt":"Log in with",
  "emailAddressTxt":"Email address",
  "continueWithEmailTxt":"Continue with Email id",
  "chooseAccountTxt":"Choose an account",
  "passwordTxt":"Password",
  "toContinueTxt": "to continue\n to Agnihotra - ek rog mukta abhiyan",
  "emailHintTxt": "Enter your Email address",
  "passwordHintTxt":"Enter your password",
  "forgetPwdTxt":"Forgot Password?",
  "addAnotherAccountTxt":"Add another account",

  // Register Screen
  "nameTxt":"Name",
  "fullNameHintTxt":"Enter your Name",
  "createAccountTxt":"Create an account",
  "signUpTxt":"Sign up",

  //Edit Profile Screen
  "editProfileTxt":"Edit Profile",
   "changeProfilePhotoTxt":"Change Profile Photo",
  "removeProfilePhotoTxt":"Remove Profile Photo",
  "cancelTxt":"Cancel",
  "userNameTxt":"User name",


  /// Forgot Password Screen
  "forgetPwdScrrenTxt":"Forgot Password",
  "enterYourEmailAddressTxt":"Enter your email address for\nreset password",
  "resetPasswordTxt":"Password Reset",

  // Reset Password Screen
  "resetPwdTxt":"Reset Password",
  "enterNewPwdTwiceTxt":"Enter your new password twice below\nto reset a new password",
  "enterNewPwdTxt":"Enter new password",
  "reEnterNewPwdTxt":"Re-enter new password",
  "reEnterPwdHintTxt":"Re-enter your new password",
  "genderTxt":"Gender",
  "updateBtnTxt":"Update",
  "selectGenderTxt":"Select Gender",
  "maleTxt":"Male",
  "femaleTxt":"Female",
  "otherTxt":"Other",
  "okTxt":"OK",



};