Map<String,String> en= {

  "locationSetTxt":"Location not set,click on icon!",
  "engTxt":"English",
  "gujTxt":"Gujarati",
  "hinTxt":"Hindi",
  "usgMapTxt" :"Use Google Maps",
  "usgManuallyTxt":"Enter Manually",
  "manuallyEntryTxt":"Manually Entry",
  "stdConveLocationTxt":"Enter location below in degrees using standard conventions",
  "notEstSouWesTxt":"(+ve for North/East and -ve for south/west)",
  "locationUseTxt":"Use this location",
  "mapLocationUseTxt":"See this location on map",
  "latiTxt":"Latitude:",
  "longTxt":"Longitude:",
  "selectTxt":"SELECT",
  "mapTxt":"map",
  "mapViewTxt":"Map View",
  "satelliteTxt":"Satellite",
  "searchTxt":"Search location",
  "searchBtnTxt" : "Search",
  "welcomeTxt":"WELCOME",
  "getStartTxt":"Let’s Get Started",
  "languageChooseTxt":"Choose Your Language",
  "languageUseTxt":"Select the language you prefer to use",
  "submitBtnTxt":"Submit",
  "mantraTxt":"Mantra",
  "SettingsScreenTxt":"Settings",
  "contactsTxt":"Contacts",
  "languageTxt":"Language",
  "aboutTxt":"About",
  "privacyPolicyTxt":"Privacy policy",
  "shareTxt":"Share",
  "helpTxt":"Help",
  "sunriseTxt":"Sunrise Mantra",
  "sunsetTxt":"Sunset Mantra",
  "playTxt":"play it",
  "checkTimeTxt":"Check time",
  "checkDeviceTimeTxt":"check your device time with time on the internet.please note that accuracy is dependent on network and third party tools-worldtimeapi.org internet.",
  "screenOnTxt":"Screen Always On",
  "screenKeepTxt":"Keeps screen awake while app is open",
  "hoursTxt":"24 Hours Clock",
  "timeTxt":"change time format to 12 or 24 hours",
  "meditationTxt":"Meditation Bell",
  "ringsTxt":"rings bell at time of this app",
  "countDownTxt":"Display Countdown",
  " countDownClockTxt":"display countdown or clock in center",
  "reminderTxt":"Reminders",
  "setReminderTxt":"set reminders for this app",
  "resetBtnTxt":"Reset",
  "deleteLocationTxt":"Delete All Location",
  "addLocationTxt":"Add Location",
  "sooryayaSwaha":"sooryaya swaha",
  "sooryayaIdem":"sooryaya idem na mama",
  "prajapatayeSwaha":"Prajapataye Swaha",
  "prajapatayeIdem":"prajapataye idem na mama",
  "agnayeSwaha":"agnaye swaha",
  "agnayeIdem":"agnaye idem na mama",
  "agnihotraMantraTxt":"Agnihotra mantra",
  "sunriseSunsetMantraTxt":"(sunrise & sunset mantra)",
  "tilakSandhyaMantraTxt":"Trikal sandhya mantra",
  "trikalMantraTxt":"Trikal Sandhya Mantra",
  "mantra24":"24 mantra",
  "timeZonTxt" :"Please confirm timesone for this location",
  "standardTime":"India Standard Time(Asia/Kolkata)",
  "changeTimeTxt" : "Change Timezone",
  "confirmTxt":"Confirm",
  "renameLocationBtnTxt":"RENAME LOCATION",
  "renameLocationTxt":"Rename this Location",
  "deleteLocationBtnTxt" : "Delete this Location",
  "enterLocationTxt":"Enter new name for location",
  "cancleTxt":"CANCEL",
  "languageValidationTxt":"Please Selected Language",
  "latitudeIsRequired":"Latitude is required",
  "validLatitude":"Enter Valid Latitude",
  "longitudeIsRequired":"Longitude is required",
  "validLongitude":"Enter Valid Latitude",
  "searchText":"Search"


};