Map<String,String> en= {

  "locationSetTxt":"Location not set,click on icon!",
  "engTxt":"English",
  "gujTxt":"Gujarati",
  "hinTxt":"Hindi",
  "usgMapTxt" :"Use Google Maps",
  "usgManuallyTxt":"Enter Manually",
  "manuallyEntryTxt":"Manually Entry",
  "stdConveLocationTxt":"Enter location below in degrees using standard conventions",
  "notEstSouWesTxt":"(+ve for North/East and -ve for south/west)",
  "locationUseTxt":"Use this location",
  "mapLocationUseTxt":"See this location on map",
  "noTxt":"NO",
  "latiTxt":"Latitude:",
  "longTxt":"Longitude:",
  "selectTxt":"SELECT",
  "mapTxt":"map",
  "mapViewTxt":"Map View",
  "satelliteTxt":"Satellite",
  "searchTxt":"Search location",
  "searchBtnTxt" : "Search",
  "welcomeTxt":"WELCOME",
  "getStartTxt":"Let’s Get Started",
  "languageChooseTxt":"Choose Your Language",
  "languageUseTxt":"Select the language you prefer to use",
  "submitBtnTxt":"Submit",
  "mantraTxt":"Mantra",
  "contactsTxt":"Contacts",
  "languageTxt":"Language",
  "aboutTxt":"About",
  "privacyPolicyTxt":"Privacy policy",
  "shareTxt":"Share",
  "helpTxt":"Help",
  "sunriseTxt":"Sunrise Mantra",
  "sunsetTxt":"Sunset Mantra",
  "playTxt":"play it",
  "checkTimeTxt":"Check time",
  "checkDeviceTimeTxt":"check your device time with time on the internet.please note that accuracy is dependent on network and third party tools-worldtimeapi.org internet.",
  "screenOnTxt":"Screen Always On",
  "screenKeepTxt":"Keeps screen awake while app is open",
  "hoursTxt":"24 Hours Clock",
  "timeTxt":"change time format to 12 or 24 hours",
  "meditationTxt":"Meditation Bell",
  "ringsTxt":"rings bell at time of this app",
  "countDownTxt":"Display Countdown",
  "countDownClockTxt":"display countdown or clock in center",
  "reminderTxt":"Reminders",
  "setReminderTxt":"set reminders for this app",
  "resetBtnTxt":"Reset",
  "deleteLocationTxt":"Delete All Location",
  "addLocationTxt":"Add Location",
  "sooryayaSwaha":"sooryaya swaha",
  "sooryayaIdem":"sooryaya idem na mama",
  "prajapatayeSwaha":"Prajapataye Swaha",
  "prajapatayeIdem":"prajapataye idem na mama",
  "agnayeSwaha":"agnaye swaha",
  "agnayeIdem":"agnaye idem na mama",
  "agnihotraMantraTxt":"Agnihotra mantra",
  "sunriseSunsetMantraTxt":"(sunrise & sunset mantra)",
  "tilakSandhyaMantraTxt":"Trikal sandhya mantra",
  "trikalMantraTxt":"Trikal Sandhya Mantra",
  "mantra24":"24 mantra",
  "timeZonTxt" :"Please confirm timesone\nfor this location",
  "standardTime":"India Standard Time(Asia/Kolkata)",
  "changeTimeTxt" : "Change Timezone",
  "confirmTimeZone" : "Confirm Timezone for your location",
  "yesTxt" : "YES",
  "timingDownload" : "Please wait,\ntiming are being downloaded.",
  "deleteAllLocation" : "Are you sure you wish to delete all\nlocations ?",
  "deleteThisLocation" : "Delete this Location?",
  "confirmTxt":"Confirm",
  "renameLocationBtnTxt":"RENAME THIS LOCATION",
  "renameLocationTxt":"Rename this Location",
  "deleteLocationBtnTxt" : "Delete this Location",
  "enterLocationTxt":"Enter new name for location",
  "cancleTxt":"CANCEL",
  "languageValidationTxt":"Please Selected Language",
  "latitudeIsRequired":"Latitude is required",
  "validLatitude":"Enter Valid Latitude",
  "longitudeIsRequired":"Longitude is required",
  "validLongitude":"Enter Valid Latitude",
  "searchText":"Search",
  "drinkWaterText":"(Drink Water)",
  "sprinklingWaterText":"(Sprinkling Water on Head)",
  "headText":"(Touch the Head)",
  "noseText":"(Touch the Nose)",
  "heartText":"(Touch the Heart)",
  "handsText":"(Hands with sandwiched palms on right knee)",
  "rightHandsText":"(Water in right hand)",
  "gayatriMantraText":"(3 time Gayatri Mantra)",
  "waterOblationText":"(Water Oblations)",
  "avahanMudraText":"(avahan mudra)",
  "meditateText":"(Meditate for Few Minutes, Start the gayatri japa and after that Meditate for some time)",
  "directionText":"(Stand up, bow towards the four direction)",
  "fireText":"(Light the Fire)",
  "pourWaterText":"(Pour Water in Following Directions)",
  "samidhaText":"(Offer Samidha)",
  "timeText":"(3/7/11 Times)",
  "oneTimeText":"(1 Times)",
  "sandipText":"(SANDIP)",
  "surrenderingText":"(Surrendering all our actions thought & their results,\noffering water)",
  "roundText":"प्राणायामे विनियोगः (5 Round)",
  "eastText":"सन्ध्यायै नमः  - East",
  "southText":"सावित्रै नमः  - South",
  "gaytrenamText":"गायत्रै नमः  - West",
  "sarswateyText":"सरस्वत्यै नमः  - North",
  "sarvabyaText":"सर्वाभ्यो देवताभ्यो नमः  - East",
  "kamkarshitText":"कामोकार्षीत मन्युकार्षीत नमो नमः   - East",
  "aditeText":"ॐ अदितेन्वमंस्ताः ॥ \n(pronounce as : अदितेन्वमग्गुस्ताः)",
  "anumatveText":"ॐ अनुमतेन्वमंस्ताः ॥ \n(pronounce as : अनुमतेन्वमग्गुस्ताः)",
  "sarswateProText":"ॐ सरस्वतेन्वमंस्ताः ||\n(pronounce as  : सरस्वतेन्वमग्गुस्ताः)",
  "applyText":"(Apply Ashes)",
  "meghaviText":"मेधावी भूयासम्\t  On fore head(third eye)",
  "tejasviText":"तेजस्वी भूयासम् \t  On Chest (Heart region)",
  "varchsviText":"वर्चस्वी भूयासम् \t  Right Shoulder",
  "brhamsviText":"ब्रह्मवर्चस्वी भूयासम\t Left Shoulder",
  "ayushyaText":"आयुष्यमान् भूयासम्\t Navel Region",
  "annadoText":"अन्नादो भूयासम्\t On Throat",
  "swstiText":"स्वस्ति भूयासम्\t Top of the head",
  "settingsScreenTxt":"Settings",
  "deleteAllLocation":"Are you sure you wish to delete all\nlocations ?",
  "processedTxt":"PROCEED",


  "SettingsScreenTxt":"Settings",

  " countDownClockTxt":"display countdown or clock in center",

  "confirmTimeZone" : "Confirm Timezone for your location",
  "yesTxt" : "YES",
  "timingDownload" : "Please wait,\ntiming are being downloaded.",

  "proceedTxt":"PROCEED",
  "indiaStdTime":"India Standard Time"


};