Map<String,String> gu = {

  "locationSetTxt":"સ્થાન સેટ નથી, આયકન પર ક્લિક કરો!",
  "engTxt":"અંગ્રેજી",
  "gujTxt":"ગુજરાતી",
  "hinTxt":"હિન્દી",
  "usgMapTxt" :"ગૂગલ મેપ્સનો ઉપયોગ કરો",
  "usgManuallyTxt":"મેન્યુઅલી દાખલ કરો",
  "manuallyEntryTxt":"મેન્યુઅલી એન્ટ્રી",
  "stdConveLocationTxt":"પ્રમાણભૂત સંમેલનોનો ઉપયોગ કરીને ડિગ્રીમાં નીચે સ્થાન દાખલ કરો",
  "agnihotraPatraText": "અગ્નિહોત્ર પાત્રનું કદ",
  "notEstSouWesTxt":"(ઉત્તર/પૂર્વ માટે +ve અને દક્ષિણ/પશ્ચિમ માટે -ve)",
  "locationUseTxt":"આ સ્થાનનો ઉપયોગ કરો",
  "mapLocationUseTxt":"નકશા પર આ સ્થાન જુઓ",
  "noTxt":"ના",
  "latiTxt":"અક્ષાંશ:",
  "longTxt":"રેખાંશ:",
  "selectTxt":"પસંદ કરો",
  "mapTxt":"નકશો",

  "mapViewTxt":"નકશો જુઓ",
  "satelliteTxt":"ઉપગ્રહ",
  "searchTxt":"સ્થાન શોધો",
  "searchBtnTxt" : "શોધો",
  "welcomeTxt":"સ્વાગત છે",
  /// Add Today
  "alertTxt":'ચેતવણી !',
  "resetMsg":'રીસેટ પૂર્ણ',
  "resetButtonNotice":"\tતમે એપને રીસેટ કરવા જઈ રહ્યાં છો જે તમામ સ્થાન સમય અને પસંદગીને કાઢી નાખશે. રીસેટ કર્યા પછી તમે નવું સ્થાન ઉમેરવા માટે સમર્થ હશો. આ વિકલ્પનો ઉપયોગ ફક્ત ડેટા ભ્રષ્ટાચાર અથવા ભૂલના કિસ્સામાં કરો.",
  "ringAlarmTxt":"દરરોજ રીંગ એલાર્મ મુ",
  /// Add Today
  "getStartTxt":"ચાલો, શરુ કરીએ",
  "languageChooseTxt":"તમારી ભાષા પસંદ કરો",
  "languageUseTxt":"તમે ઉપયોગ કરવાનું પસંદ કરો છો તે ભાષા પસંદ કરો",

  "submitBtnTxt":"સબમિટ કરો",
  "mantraTxt":"મંત્ર",
  "contactsTxt":"સંપર્કો",
  "languageTxt":"ભાષા",
  "aboutTxt":"વિશે",
  "privacyPolicyTxt":"ગોપનીયતા નીતિ",
  "shareTxt":"શેર કરો",
  "helpTxt":"મદદ",
  "sunriseTxt":"સૂર્યોદય મંત્ર",
  "sunsetTxt":"સૂર્યાસ્ત મંત્ર",
  "playTxt":"શરૂ કરો",
  "checkTimeTxt":"તમારા સમયની ખાતરી કરો",
  "checkDeviceTimeTxt":"ઇન્ટરનેટ પર સમય સાથે તમારા ઉપકરણનો સમય તપાસો. કૃપા કરીને નોંધો કે ચોકસાઈ નેટવર્ક અને થર્ડ પાર્ટી ટૂલ્સ-worldtimeapi.org ઇન્ટરનેટ પર આધારિત છે.",
  "screenOnTxt":"સ્ક્રીન હંમેશા ચાલુ",
  "screenKeepTxt":"એપ્લિકેશન ખુલ્લી હોય ત્યારે સ્ક્રીન હંમેશાં ચાલુ રાખે છે",
  "hoursTxt":"24 કલાક ઘડિયાળ",
  "timeTxt":"સમયને 24 કલાકમાં બદલો",
  "meditationTxt":"ધ્યાન ઘંટડી",
  "ringsTxt":"અગ્નિહોત્ર સમયે બેલ વાગે છે",
  "countDownTxt":"ડિસ્પ્લે કાઉન્ટડાઉન",
  "countDownClockTxt":"મધ્યમાં નેક્ષ્ટ અગ્નિહોત્રના સમયની ઊંધીગણત્રી અથવા ઘડિયાળ દર્શાવો",
  "reminderTxt":"રીમાઇન્ડર્સ",
  "setReminderTxt":" અગ્નિહોત્ર માટે રીમાઇન્ડર્સ સેટ કરો",
  "resetBtnTxt":"રીસેટ",
  "deleteLocationTxt":"બધા સ્થાન કાઢી નાખો",
  "addLocationTxt":"સ્થાન ઉમેરો",
  "sooryayaSwaha":"સૂર્યાય સ્વાહા",
  "sooryayaIdem":"સૂર્યયા ઇદેમ ના મામા",
  "prajapatayeSwaha":"પ્રજાપતયે સ્વાહા",
  "prajapatayeIdem":"પ્રજાપતયે ઇદેમ ના મા",
  "agnayeSwaha":"અગ્નયે સ્વાહા",
  "agnayeIdem":"અગ્નયે ઈદમ ના મામા",
  "agnihotraMantraTxt":"।। અગ્નિહોત્ર ।।",
  "sunriseSunsetMantraTxt":".... સૂર્યોદય અને સૂર્યાસ્ત સમય ના મંત્ર ....",
  "tilakSandhyaMantraTxt":"ત્રિકાલ સંધ્યા મંત્ર",
  "trikalMantraTxt":"।। ત્રિકાલ સંધ્યા ।। ",
  "mantra24":"24 મંત્ર",
  "timeZonTxt":"કૃપા કરીને આ સ્થાન માટે\nસમયની પુષ્ટિ કરો",
  "standardTime":"ભારતીય માનક સમય(એશિયા/કોલકાતા)",
  "changeTimeTxt" : "ટાઇમઝોન બદલો",
  "confirmTxt":"પુષ્ટિ કરો",
  "renameLocationBtnTxt":"સ્થાનનું નામ બદલો",
  "renameLocationTxt":"આ સ્થાનનું નામ બદલો",
  "deleteLocationBtnTxt" : "આ સ્થાન કાઢી નાખો",
  "enterLocationTxt":"સ્થાન માટે નવું નામ દાખલ કરો",
  "cancleTxt":"રદ કરો",
  "languageValidationTxt":"કૃપા કરીને ભાષા પસંદ કરો",
  "latitudeIsRequired":"અક્ષાંશ જરૂરી છે",
  "validLatitude":"માન્ય અક્ષાંશ દાખલ કરો",
  "longitudeIsRequired":"રેખાંશ જરૂરી છે",
  "validLongitude":"માન્ય અક્ષાંશ દાખલ કરો",
  "searchText":"શોધો",
  "drinkWaterText":"(પાણી પીવો)",
  "sprinklingWaterText":"(માથા પર પાણી છાંટો)",
  "headText":"(માથાને ટચ કરો)",
  "noseText":"(નાકને ટચ કરો)",
  "heartText":"(હૃદયને ટચ કરો)",
  "handsText":"(જમણા હાથની હથેળી ઉપર ડાબા હાથની હથેળી બંધ કરીને જમણા પગના ઘૂંટણ પર મૂકો)",
  "rightHandsText":"(જમણા હાથમાં પાણી લ્યો)",
  "gayatriMantraText":"(3 વાર ગાયત્રી મંત્ર બોલો)",
  "waterOblationText":"(પાણીને અર્પણ કરી દયો)",
  "avahanMudraText":"(આવાહન મુદ્દા)",
  "meditateText":"(થોડી મિનિટ ધ્યાન કરો, ગાયત્રી જાપ શરૂ કરો અને ત્યારબાદ થોડીવાર ધ્યાન કરો)",
  "directionText":"(ઊભા થાવ અને વારાફરતી ચારે-દિશા તરફ ઝુકીને પ્રણામ કરો)",
  "fireText":"(અગ્નિ પ્રગટાવો)",
  "pourWaterText":"(નીચેની દિશાઓમાં પાણી રેડો)",
  "samidhaText":"(સમિધા અર્પણ કરો)",
  "timeText":"(3/7/11 વખત)",
  "oneTimeText":"(1 વખત)",
  "sandipText":"(સંદીપ)",
  "surrenderingText":"(આપણી બધી ક્રિયાઓના વિચારો અને તેના પરિણામને સમર્પણ કરીને,\nપાણી અર્પણ કરો)",
  "roundText":"प्राणायामे विनियोगः (5 રાઉન્ડ)",
  "eastText":"सन्ध्यायै नमः  - પૂર્વ દિશામાં",
  "southText":"सावित्रै नमः  - દક્ષિણ દિશામાં",
  "gaytrenamText":"गायत्रै नमः  - પશ્ચિમ દિશામાં",
  "sarswateyText":"सरस्वत्यै नमः  - ઉત્તર દિશામાં",
  "sarvabyaText":"सर्वाभ्यो देवताभ्यो नमः  - પૂર્વ દિશામાં",
  "kamkarshitText":"कामोकार्षीत मन्युर्कार्षीत नमो नमः   - પૂર્વ દિશામાં",
  "aditeText":"ॐ अदितेन्वमंस्ताः ॥ \n(આ રીતે ઉચ્ચારવામાં આવે છે : अदितेन्वमग्गुस्ताः)",
  "anumatveText":"ॐ अनुमतेन्वमंस्ताः ॥ \n(આ રીતે ઉચ્ચારવામાં આવે છે : अनुमतेन्वमग्गुस्ताः)",
  "sarswateProText":"ॐ सरस्वतेन्वमंस्ताः ||\n(આ રીતે ઉચ્ચારવામાં આવે છે  : सरस्वतेन्वमग्गुस्ताः)",
  "applyText":"(રાખ (ભસ્મ) લગાવો)",
  "meghaviText":"मेधावी भूयासम्\t\t\t\t\t\t\t\t\t\tકપાળ પર(બંને ભમરોની વચ્ચે)",
  "tejasviText":"तेजस्वी भूयासम्\t\t\t\t\t\t\t\t\tછાતી પર (હૃદયના સ્થાને)",
  "varchsviText":"वर्चस्वी भूयासम्\t\t\t\t\t\t\t\t\t\tજમણો ખભા પર",
  "brhamsviText":"ब्रह्मवर्चस्वी भूयासम\t\t\t\t\tડાબા ખભા પર",
  "ayushyaText":"आयुष्यमान् भूयासम्\t\t\t\tનાભિ ઉપર",
  "annadoText":"अन्नादो भूयासम्\t\t\t\t\t\t\t\t\t\t\tગળા ભાગ પર(વિશુદ્રી ચક્ર પર)",
  "swstiText":"स्वस्ति भूयासम्\t\t\t\t\t\t\t\t\t\t\t\tમાથાની ચોટી પર",
  "settingsScreenTxt":"સેટિંગ્સ",
  "deleteAllLocation":"શું તમે ખરેખર બધા\nસ્થાનો કાઢી નાખવા માંગો છો?",
  "deleteThisLocation" : "આ સ્થાન કાઢી નાખીએ?",
  "proceedTxt":"આગળ વધો",
  "appName": "અગ્નિહોત્ર - એક રોગ મુક્ત અભિયાન",
  "inspiration":"પ્રેરણા:",
  "guruName": "ગુરુદેવ શ્રી શ્રી રવિશંકર",
  "yesTxt" : "હા",
  "callHelpLine":'હેલ્પલાઈન પર ફોન કરો',
  "emailSupport":'ઇમેઇલ આધાર',
  "chatSupport":'આધાર સાથે ચેટ કરો',
  "feedback":'પ્રતિભાવ'



};