Map<String,String> gu = {

  "locationSetTxt":"સ્થાન સેટ નથી, આયકન પર ક્લિક કરો!",
  "engTxt":"અંગ્રેજી",
  "gujTxt":"ગુજરાતી",
  "hinTxt":"હિન્દી",
  "usgMapTxt" :"ગૂગલ મેપ્સનો ઉપયોગ કરો",
  "usgManuallyTxt":"મેન્યુઅલી દાખલ કરો",
  "manuallyEntryTxt":"મેન્યુઅલી એન્ટ્રી",
  "stdConveLocationTxt":"પ્રમાણભૂત સંમેલનોનો ઉપયોગ કરીને ડિગ્રીમાં નીચે સ્થાન દાખલ કરો",
  "notEstSouWesTxt":"(ઉત્તર/પૂર્વ માટે +ve અને દક્ષિણ/પશ્ચિમ માટે -ve)",
  "locationUseTxt":"આ સ્થાનનો ઉપયોગ કરો",
  "mapLocationUseTxt":"નકશા પર આ સ્થાન જુઓ",
  "latiTxt":"અક્ષાંશ:",
  "longTxt":"રેખાંશ:",
  "selectTxt":"પસંદ કરો",
  "mapTxt":"નકશો",
  "mapViewTxt":"નકશો જુઓ",
  "satelliteTxt":"ઉપગ્રહ",
  "searchTxt":"સ્થાન શોધો",
  "searchBtnTxt" : "શોધો",
  "welcomeTxt":"સ્વાગત છે",
  "getStartTxt":"ચાલો, શરુ કરીએ",
  "languageChooseTxt":"તમારી ભાષા પસંદ કરો",
  "submitBtnTxt":"સબમિટ કરો",
  "mantraTxt":"મંત્ર",
  "SettingsScreenTxt":"સેટિંગ્સ",
  "contactsTxt":"સંપર્કો",
  "languageTxt":"ભાષા",
  "aboutTxt":"વિશે",
  "privacyPolicyTxt":"ગોપનીયતા નીતિ",
  "shareTxt":"શેર કરો",
  "helpTxt":"મદદ",
  "sunriseTxt":"સૂર્યોદય મંત્ર",
  "sunsetTxt":"સૂર્યાસ્ત મંત્ર",
  "playTxt":"આ રમો",
  "checkTimeTxt":"સમય તપાસો",
  "checkDeviceTimeTxt":"ઇન્ટરનેટ પર સમય સાથે તમારા ઉપકરણનો સમય તપાસો. કૃપા કરીને નોંધો કે ચોકસાઈ નેટવર્ક અને થર્ડ પાર્ટી ટૂલ્સ-worldtimeapi.org ઇન્ટરનેટ પર આધારિત છે.",
  "screenOnTxt":"સ્ક્રીન હંમેશા ચાલુ",
  "screenKeepTxt":"એપ્લિકેશન ખુલ્લી હોય ત્યારે સ્ક્રીનને જાગૃત રાખે છે",
  "hoursTxt":"24 કલાક ઘડિયાળ",
  "timeTxt":"સમય ફોર્મેટને 12 અથવા 24 કલાકમાં બદલો",
  "meditationTxt":"ધ્યાન ઘંટડી",
  "ringsTxt":"આ એપના સમયે બેલ વાગે છે",
  "countDownTxt":"ડિસ્પ્લે કાઉન્ટડાઉન",
  "countDownClockTxt":"મધ્યમાં કાઉન્ટડાઉન અથવા ઘડિયાળ દર્શાવો",
  "reminderTxt":"રીમાઇન્ડર્સ",
  "setReminderTxt":"આ એપ્લિકેશન માટે રીમાઇન્ડર્સ સેટ કરો",
  "resetBtnTxt":"રીસેટ કરો",
  "deleteLocationTxt":"બધા સ્થાન કાઢી નાખો",
  "addLocationTxt":"સ્થાન ઉમેરો",
  "sooryayaSwaha":"સૂર્યાય સ્વાહા",
  "sooryayaIdem":"સૂર્યયા ઇદેમ ના મામા",
  "prajapatayeSwaha":"પ્રજાપતયે સ્વાહા",
  "prajapatayeIdem":"પ્રજાપતયે ઇદેમ ના મા",
  "agnayeSwaha":"અગ્નયે સ્વાહા",
  "agnayeIdem":"અગ્નયે ઈદમ ના મામા",
  "agnihotraMantraTxt":"અગ્નિહોત્ર મંત્ર",
  "sunriseSunsetMantraTxt":"(સૂર્યોદય અને સૂર્યાસ્ત મંત્ર)",
  "tilakSandhyaMantraTxt":"ત્રિકાલ સંધ્યા મંત્ર",
  "trikalMantraTxt":"ત્રિકાલ સંધ્યા મંત્ર",
  "mantra24":"24 મંત્ર",
  "timeZonTxt":"કૃપા કરીને આ સ્થાન માટે સમયની પુષ્ટિ કરો",
  "standardTime":"ભારતીય માનક સમય(એશિયા/કોલકાતા)",
  "changeTimeTxt" : "ટાઇમઝોન બદલો",
  "confirmTxt":"પુષ્ટિ કરો",
  "renameLocationBtnTxt":"સ્થાનનું નામ બદલો",
  "renameLocationTxt":"આ સ્થાનનું નામ બદલો",
  "deleteLocationBtnTxt" : "આ સ્થાન કાઢી નાખો",
  "enterLocationTxt":"સ્થાન માટે નવું નામ દાખલ કરો",
  "cancleTxt":"રદ કરો",
  "languageValidationTxt":"કૃપા કરીને ભાષા પસંદ કરો",
  "latitudeIsRequired":"અક્ષાંશ જરૂરી છે",
  "validLatitude":"માન્ય અક્ષાંશ દાખલ કરો",
  "longitudeIsRequired":"રેખાંશ જરૂરી છે",
  "validLongitude":"માન્ય અક્ષાંશ દાખલ કરો",


};