Map<String, String> hi = {

  "locationSetTxt": "स्थान निर्धारित नहीं है, आइकन पर क्लिक करें!",
  "engTxt": "अंग्रेज़ी",
  "gujTxt": "गुजराती",
  "hinTxt": "हिंदी",
  "usgMapTxt": "गूगल मेप का उपयोग करे",
  "usgManuallyTxt": "मैन्युअल रूप से दर्ज़ करें",
  "manuallyEntryTxt": "मैन्युअल रूप से प्रवेश",
  "stdConveLocationTxt": "मानक परंपराओं का उपयोग करके नीचे डिग्री में स्थान दर्ज करें",
  "notEstSouWesTxt": "(उत्तर/पूर्व के लिए +ve और दक्षिण/पश्चिम के लिए -ve)",
  "locationUseTxt": "इस स्थान का उपयोग करें",
  "mapLocationUseTxt": "मानचित्र पर यह स्थान देखें",
  "noTxt": "नहीं",
  "latiTxt": "अक्षांश:",
  "longTxt": "देशांतर:",
  "selectTxt": "चुनना",
  "mapTxt": "नक्शा",
  "mapViewTxt": "नक्शा देखें",
  "satelliteTxt": "उपग्रह",
  "searchTxt": "स्थान खोजें",
  "searchBtnTxt": "खोज",
  "welcomeTxt": "स्वागत",
  "getStartTxt": "आएँ शुरू करें",
  "languageChooseTxt": "अपनी भाषा चुनें",
  "languageUseTxt": "वह भाषा चुनें जिसका आप उपयोग करना पसंद करते हैं",
  "submitBtnTxt": "जमा करना",
  "mantraTxt": "मंत्र",
  "contactsTxt": "संपर्क",
  "languageTxt": "भाषा",
  "aboutTxt": "के बारे में",
  "privacyPolicyTxt": "गोपनीयता नीति",
  "shareTxt": "शेयर करना",
  "helpTxt": "मदद",
  "sunriseTxt": "सूर्योदय मंत्र",

  "alertTxt": 'चेतावनी !',
  "resetButtonNotice": '\tआप ऐप को रीसेट करने वाले हैं जो सभी स्थान समय और वरीयताएँ हटा देगा। आप रीसेट के बाद नया स्थान जोड़ने में सक्षम होंगे। डेटा भ्रष्टाचार या त्रुटि के मामले में केवल इस विकल्प का उपयोग करें।',
  "resetMsg": 'रीसेट पूर्ण',
  "ringAlarmTxt": "पर अनुस्मारक सेट करें",

  "sunsetTxt": "सूर्यास्त मंत्र",
  "playTxt": "शुरु करें",
  "checkTimeTxt": "अपना समय जांचें",
  "checkDeviceTimeTxt": "इंटरनेट पर समय के साथ अपने डिवाइस का समय जांचें। कृपया ध्यान दें कि सटीकता नेटवर्क और तीसरे पक्ष के टूल-worldtimeapi.org इंटरनेट पर निर्भर है।",
  "screenOnTxt": "स्क्रीन हमेशा चालू",
  "screenKeepTxt": "ऐप खुला रहने पर स्क्रीन को शुरू रखता है",
  "hoursTxt": "24 घंटे की घड़ी",
  "timeTxt": "समयको 24 घंटे में बदलें",
  "meditationTxt": "ध्यान घंटी",
  "ringsTxt": "अग्निहोत्र के समय घंटी बजती है",
  "countDownTxt": "उलटी गिनती प्रदर्शित करें",
  "countDownClockTxt": "केंद्र में उलटी गिनती या घड़ी प्रदर्शित करें",
  "reminderTxt": "सूर्यास्त के समय के लिए अनुस्मारक",
  "sunriseReminderTxt": "सूर्योदय के समय के लिए अनुस्मारक",
  "setReminderTxt": "अग्निहोत्र के लिए अनुस्मारक सेट करें",
  "resetBtnTxt": "रीसेट",
  "deleteLocationTxt": "सभी स्थान हटाएँ",
  "addLocationTxt": "स्थान जोड़ना",
  "sooryayaSwaha": "सूर्याय स्वाहा",
  "sooryayaIdem": "सूर्याय इदेम न मम",
  "prajapatayeSwaha": "प्रजापतये स्वाहा",
  "prajapatayeIdem": "प्रजापतये इदेम् न मम",
  "agnayeSwaha": "अग्नये स्वाहा",
  "agnayeIdem": "अग्नये इदं न मम",
  "agnihotraMantraTxt": "।। अग्निहोत्र।।",
  "sunriseSunsetMantraTxt": ".... सूर्योदय और सूर्यास्त मंत्र....",
  "tilakSandhyaMantraTxt": "त्रिकाल संध्या मंत्र",
  "agnihotraPatraText": "अग्निहोत्र पात्र का आकार",
  "trikalMantraTxt": "।। त्रिकाल संध्या ll",
  "mantra24": "24 मंत्र",
  "timeZonTxt": "कृपया इस स्थान के लिए\nटाइमवन की पुष्टि करें",
  "standardTime": "भारतीय मानक समय(एशिया/कोलकाता)",
  "changeTimeTxt": "समयक्षेत्र बदलें",
  "confirmTxt": "पुष्टि करना",
  "renameLocationBtnTxt": "स्थान का नाम बदलें",
  "renameLocationTxt": "इस स्थान का नाम बदलें",
  "deleteLocationBtnTxt": "यह स्थान हटाएं",
  "enterLocationTxt": "स्थान के लिए नया नाम दर्ज करें",
  "cancleTxt": "रद्द करना",
  "languageValidationTxt": "कृपया चयनित भाषा",
  "latitudeIsRequired": "अक्षांश आवश्यक है",
  "validLatitude": "मान्य अक्षांश दर्ज करें",
  "longitudeIsRequired": "देशांतर आवश्यक है",
  "validLongitude": "मान्य अक्षांश दर्ज करें",
  "searchText": "खोज",
  "drinkWaterText": "(पानी पियें)",
  "sprinklingWaterText": "(सिर पर पानी छिड़कते हुए)",
  "headText": "(सिर पर हाथ फेरें)",
  "noseText": "(नाक छुओ)",
  "heartText": "(हृदय को छू लें)",
  "handsText": "(दाहिने घुटने पर फटी हथेलियों वाले सैकड़ों लोग)",
  "rightHandsText": "(दाहिने हाथ में जल)",
  "gayatriMantraText": "(3 बार गायत्री मंत्र बोलिये)",
  "waterOblationText": "(जल अर्पण)",
  "avahanMudraText": "(आवाहनमुद्रा)",
  "meditateText": "(कुछ मिनट ध्यान करें, गायत्री जप शुरू करें और उसके बाद कुछ देर ध्यान करें)",
  "directionText": "(खड़े हो जाओ, सभी दिशाओं को प्रणाम करें)",
  "fireText": "(आग जलाओ)",
  "pourWaterText": "(निम्नलिखित दिशाओं में पानी डालें)",
  "samidhaText": "(ऑफरसिमिधा)",
  "timeText": "(3/7/11 टाइम्स)",
  "oneTimeText": "(1 बार)",
  "sandipText": "(संदीप)",
  "surrenderingText": "(हमारे सभी कार्यों, विचारों और उनके परिणामों को समर्पित करते हुए,\nजल अर्पित करते हुए)",
  "roundText": "प्राणायामे विनियोगः (5 राउंड)",
  "enterTimeInMinText":"समय मिनटों में दर्ज करें (2-120):",
  "eastText": "सन्ध्यायै नमः  - पूर्व",
  "southText": "सावित्रै नमः  - दक्षिण",
  "gaytrenamText": "गायत्रै नमः  - पश्चिम",
  "sarswateyText": "सरस्वत्यै नमः  - उत्तर",
  "sarvabyaText": "सर्वाभ्यो देवताभ्यो नमः  - पूर्व",
  "kamkarshitText": "कामोकार्षीत मन्युर्कार्षीत नमो नमः  - पूर्व",
  "aditeText": "ॐ अदितेन्वमंस्ताः ॥ \n(इस प्रकार उच्चारित करें : अदितेन्वमग्गुस्ताः)",
  "anumatveText": "ॐ अनुमतेन्वमंस्ताः ॥ \n(इस प्रकार उच्चारित करें : अनुमतेन्वमग्गुस्ताः)",
  "sarswateProText": "ॐ सरस्वतेन्वमंस्ताः ||\n(इस प्रकार उच्चारित करें  : सरस्वतेन्वमग्गुस्ताः)",
  "applyText": "(परख लागू करें)",
  "meghaviText": "मेधावी भूयासम्\t\t\t\t\t\t\t\t\t\tसामने सिर पर (तीसरी आँख)",
  "tejasviText": "तेजस्वी भूयासम्\t\t\t\t\t\t\t\t\tछाती पर (हृदय क्षेत्र)",
  "varchsviText": "वर्चस्वी भूयासम्\t\t\t\t\t\t\t\t\t\tदायां कंधा",
  "brhamsviText": "ब्रह्मवर्चस्वी भूयासम\t\t\t\t\t\t\tबायाँ कंधा",
  "ayushyaText": "आयुष्यमान् भूयासम्\t\t\t\t\t\tनौसेना क्षेत्र",
  "annadoText": "अन्नादो भूयासम्\t\t\t\t\t\t\t\t\t\t\tगले पर",
  "swstiText": "स्वस्ति भूयासम्\t\t\t\t\t\t\t\t\t\t\t\tसिर के ऊपर",
  "settingsScreenTxt": "समायोजन",
  "deleteAllLocation": "क्या आप वाकई सभी\nस्थानों को हटाना चाहते हैं?",
  "deleteThisLocation": "यह स्थान हटाएं?",
  "proceedTxt": "आगे बढ़ो",
  "appName": "अग्निहोत्र - एक रोग मुक्त अभियान",
  "inspiration": "प्रेरणा:",
  "guruName": "गुरुदेव श्री श्री रविशंकर",
  "yesTxt": "हाँ",
  "callHelpLine": 'हेल्पलाइन पर कॉल करें',
  "emailSupport": 'ई - मेल समर्थन',
  "chatSupport": 'समर्थन के साथ चैट करें',
  "feedback": 'प्रतिक्रिया',
  'pauseTxt': 'इसे रोकें',
  'search': 'खोज',
  'confirmTimeZone': 'अपने स्थान के लिए समयक्षेत्र की पुष्टि करें',
  "teamAgnihotraTxt": 'टीम अग्निहोत्र',
  "feedbackOptionTxt": "कृपया फीडबैक साझा करने या परेशानी बताने के लिए एक विकल्प चुनें",
  "shareFeedbackTxt": "मैं एक प्रतिक्रिया साझा करना चाहता हूं",
  "shareBotherationTxt": "मैं परेशानी बताना चाहता हूं",
  "sendBtnTxt": "भेजना",
  "matraTxt": "मंत्र",

  // Login Screen
  "doNotHaveAccountTxt": "आपके पास कोई खाता नहीं है?",
  "loginTxt": 'लॉग इन करें',
  "continueGoogleTxt": "गूगल के साथ जारी रखें",
  "orSignInWithTxt": 'या इसके साथ साइन इन करें',
  "orTxt": "या",
  "logInWithTxt": "साथ प्रवेश करना",
  "continueWithEmailTxt": "ईमेल आईडी जारी रखें",
  "chooseAccountTxt": "एक खाता चुनें",
  "toContinueTxt": "जारी रखने के लिए\nअग्निहोत्र को - एक रोग मुक्त अभियान",
  "emailHintTxt": "अपना ईमेल पता दर्ज करें",
  "passwordHintTxt": "अपना पासवर्ड भरें",
  "passwordTxt": "पासवर्ड",
  "emailAddressTxt": "ई-मेल एड्रेस",
  "forgetPwdTxt": "पासवर्ड भूल गए?",
  "addAnotherAccountTxt": "दूसरा खाता जोड़ें",

  // Register Screen
  "nameTxt": "नाम",
  "fullNameHintTxt": "अपना नाम दर्ज करें",
  "createAccountTxt": "खाता बनाएं",
  "signUpTxt": "साइन अप करें",


  //Edit Profile Screen
  "editProfileTxt": "प्रोफ़ाइल संपादित करें",
  "changeProfilePhotoTxt":"प्रोफ़ाइल फ़ोटो बदलें",
  "removeProfilePhotoTxt":"प्रोफ़ाइल फ़ोटो हटाएँ",
  "cancelTxt":"रद्द करना",
  "userNameTxt":"उपयोगकर्ता नाम",





  // Forgot Password Screen
  "forgetPwdScrrenTxt": "पासवर्ड भूल गए",
  "enterYourEmailAddressTxt": "पासवर्ड रीसेट करने के लिए अपना ईमेल पता दर्ज करें",
  "resetPasswordTxt": "पासवर्ड रीसेट",

  // Reset Password Screen
  "resetPwdTxt":"पासवर्ड रीसेट",
  "enterNewPwdTwiceTxt":"नया पासवर्ड रीसेट करने के लिए नीचे अपना नया\nपासवर्ड दो बार दर्ज करें",
  "enterNewPwdTxt":"નવો પાસવર્ડ દાખલ કરો",
  "reEnterNewPwdTxt":"नया पासवर्ड पुनः दर्ज करें",
  "reEnterPwdHintTxt":"अपना नया पासवर्ड पुनः दर्ज करें",
  "genderTxt":"जाति",
  "updateBtnTxt":"अद्यतन",
  "selectGenderTxt":"जाति चुनें",
  "maleTxt":"पुरुष",
  "femaleTxt":"महिला",
  "otherTxt":"अन्य",
  "okTxt":"ठीक है",








};